### ISSUE TITLE
Background subtraction in LensHaloH and LensHaloHP

### ISSUE THREAD

**Issue by rbmetcalf** [glenco/SLsimLib#169]

**Comment by rbmetcalf** [comment]
This is the absolute value of the deflection from LensHaloH when the background is turned on 
for 1000 identical randomly positioned halos.

It looks much more reasonable when the background is 0.

<img width="509" height="508" alt="Image" src="https://github.com/user-attachments/assets/6239f7d3-507e-4779-b29a-5cf7ee5d54f3" />

**Comment by rbmetcalf** [comment]
Here is the code I'm using to test it.
```
/* ParticleExample
 no recenter on particle files
 */

#include <slsimlib.h>
#include <sstream>
#include <iomanip>
#include <omp.h>
#include <thread>
#include <mutex>
#include <math.h>


#include "gridmap.h"
#include "utilities.h"
#include "utilities_slsim.h"
#include "lens_halos.h"
#include "particle_halo2.h"
#include "disk.h"


using namespace std;

int main(int arg,char **argv){

  time_t to;
  time(&to);

  long seed = -18293;
  Utilities::RandomNumbers_NR ran(seed);
  COSMOLOGY cosmo(CosmoParamSet::Planck18);
  double zl=0.5,zs=3;
  double Dl = cosmo.angDist(zl);

  double mass = 1.0e14,q=0.7,R=0.25;
  double pa = PI/4;
  double sigma = LensHaloTNSIE::calc_sigma(mass,R,0,q);
  
  double range = 50*arcminTOradians;
  int Nhalos = 1000;

  Point_2d center(0,0);
  std::vector<LensHaloTNSIE> halos;
  for(int i=0 ; i<Nhalos ; ++i){
    double x = range*ran() - range/2;
    double y = range*ran() - range/2;
    halos.push_back(LensHaloTNSIE(mass,zl, sigma, 0, q, pa, cosmo));
    halos.back().setTheta(x,y);
  }

  Point_2d lower_left(-range/2,-range/2);
  Point_2d upper_right(range/2,range/2);
  lower_left *= 1.01;
  upper_right *= 1.01;

  //LensHaloH<LensHaloTNSIE> treeh(halos,zl,1.0/range/range,arcminTOradians,cosmo);
  //LensHaloHP<LensHaloTNSIE> treeh(halos,zl,lower_left,upper_right,arcminTOradians,cosmo);

  std::vector<Point_3d<float> > pvector(Nhalos);
  for(int i=0 ; i<Nhalos ; ++i){
    pvector[i][0] = halos[i].getTheta()[0]*Dl;
    pvector[i][1] = halos[i].getTheta()[1]*Dl;
    pvector[i][2] = 0;
  }
  //LensHaloParticles<float> treeh(pvector,zl,1.0/range/range/Dl/Dl      /// inverse area for mass compensation
  //  ,1.0e12,cosmo
  //);

  LensHaloParticlesP<float> treeh(pvector,zl,1.0/range/range/Dl/Dl      /// inverse area for mass compensation
    ,1.0e12,lower_left,upper_right,cosmo
  );

  Lens lens(&seed,zs,cosmo);
  lens.moveinMainHalo(treeh,true);

  GridMap gmap(&lens,500,center.x,3*range);
  
  gmap.writeFitsUniform<float>(LensingVariable::KAPPA,"kappa.fits");
  gmap.writeFitsUniform<float>(LensingVariable::GAMMA,"gamma.fits");
  gmap.writeFitsUniform<float>(LensingVariable::GAMMA1,"gamma1.fits");
  gmap.writeFitsUniform<float>(LensingVariable::GAMMA2,"gamma2.fits");
  gmap.writeFitsUniform<float>(LensingVariable::GAMMA3,"gamma3.fits");
  gmap.writeFitsUniform<float>(LensingVariable::ALPHA,"alpha.fits");
  gmap.writeFitsUniform<float>(LensingVariable::ALPHA1,"alpha1.fits");
  gmap.writeFitsUniform<float>(LensingVariable::ALPHA2,"alpha2.fits");
  gmap.writeFitsUniform<float>(LensingVariable::EigenV,"eigenv.fits");
  gmap.writeFitsUniform<float>(LensingVariable::INVMAG,"invmag.fits");
  
}

```

**Comment by rbmetcalf** [comment]
I think it is all fixed now.

**Comment by camilaolave** [comment]
I'm testing the new LensHaloH and I'm getting fewer critical curves passing the criteria of the minimum Einstein radius (0.5), hence less windows. inv_area apparently is too large so it's making critical curves to shrink or disappear. 

I will run some diagnostics and see what could be causing it.

**Comment by rbmetcalf** [comment]
Are you using the right units for the inv_area?  It should be in physical Mpc^-2 , not radians.

**Comment by camilaolave** [comment]
Yes, im using physical units and im still getting fewer windows

**Comment by rbmetcalf** [comment]
Try it with LensHaloHP.

Can I see your code?

**Comment by rbmetcalf** [comment]
I think inv_area_angle is changing on each shell according range of lenses on that shell.
Because there can be few, maybe one, on a shell it can be very large.

You should keep  inv_area_angle fixed to the angular scale of the whole field.  The only 
change on each shell should be in 
```
inv_area_phys = inv_area_angel/D_shelll/D_shell
```

**Comment by rbmetcalf** [comment]
It might be confusing that `inv_area` is in physical area and `hole_radius` is in radians.  There is a reason for this, but it isn't a very good reason.

I would change 'hole_radius' to physical Mpc to make them consistent.

The problem that comes up is that you can change the redshift of `LensHalo`s, which will make the angular scales of internal parameters different.

**Comment by rbmetcalf** [comment]
Remember to pull the latest version.

**Comment by rbmetcalf** [comment]
/* ParticleExample
 no recenter on particle files
 */

#include <slsimlib.h>
#include <sstream>
#include <iomanip>
#include <omp.h>
#include <thread>
#include <mutex>
#include <math.h>


#include "gridmap.h"
#include "utilities.h"
#include "utilities_slsim.h"
#include "lens_halos.h"
#include "particle_halo2.h"
#include "disk.h"


using namespace std;

int main(int arg,char **argv){

  time_t to;
  time(&to);

  long seed = -18763393;
  Utilities::RandomNumbers_NR ran(seed);
  COSMOLOGY cosmo(CosmoParamSet::Planck18);
  double zl=0.5,zs=3;
  double Dl = cosmo.angDist(zl);

  double sigma = 300;
  double mass = 1.0e13,q=1.0;//,R=20*0.25;
  double pa = PI/4;
  //double sigma = LensHaloTNSIE::calc_sigma(mass,R,0,q);
  
  double range = 3*arcminTOradians;
  int Nhalos = 100;

  Point_2d center(0,0);
  std::vector<LensHaloTNSIE> halos;
  for(int i=0 ; i<Nhalos ; ++i){
    double x = range*ran() - range/2;
    double y = range*ran() - range/2;
    halos.push_back(LensHaloTNSIE(mass,zl, sigma, 0.0*arcsecTOradians, q, pa, cosmo));
    halos.back().setTheta(x,y);
  }

  Point_2d lower_left(-range/2,-range/2);
  Point_2d upper_right(range/2,range/2);
  lower_left *= 1.01;
  upper_right *= 1.01;

  std::vector<Point_3d<float> > pvector(Nhalos);
  std::vector<float> masses(Nhalos,mass);
  for(int i=0 ; i<Nhalos ; ++i){
    pvector[i][0] = halos[i].getTheta()[0]*Dl;
    pvector[i][1] = halos[i].getTheta()[1]*Dl;
    pvector[i][2] = 0;
  }
  /*
  LensHaloParticles<float> treeh(pvector,zl,1.0/range/range/Dl/Dl      /// inverse area for mass compensation
    ,1.0e12,cosmo
    ,5 // smoothing
    ,1. // bucket size
    ,0 // opening angle
  );
  */
 /*
  LensHaloParticlesP<float> treeh(pvector,zl,1.0/range/range/Dl/Dl      /// inverse area for mass compensation
    ,1.0e12,lower_left,upper_right,cosmo
    ,6 // smoothing
    ,5 // bucket size
    ,0.1 // opening angle
  );
  */

  /**
  LensHaloParticlesO<float> treeh(pvector,zl,1.0/range/range/Dl/Dl     /// inverse area for mass compensation
      ,1.0e12   /// rescale particle masses
      ,center*Dl         /// center of hole in comoving Mpc
      ,10*arcminTOradians*Dl       /// radius of hole physical Mpc
      ,cosmo  /// cosmology
      ,1      /// number of neighbours for adaptive smoothing
      ,1       /// buckets size in tree
      ,0.1       /// opening angle for tree
    );
  */
 /*
  LensHaloParticlesM<float> treeh(pvector,zl,1.0/range/range/Dl/Dl     /// inverse area for mass compensation
      ,masses   /// rescale particle masses
      ,cosmo  /// cosmology
      ,1      /// number of neighbours for adaptive smoothing
      ,1       /// buckets size in tree
      ,0.1       /// opening angle for tree
  );
  */

  /*
  LensHaloH<LensHaloTNSIE> treeh(halos,zl
    ,1.0/range/range/Dl/Dl
    ,0.5*arcminTOradians // hole radius in radians
    ,cosmo
    ,5 // bucket size
    ,0.1 // opening angle
    );
  */
 
  LensHaloHP<LensHaloTNSIE> treeh(halos,zl,lower_left,upper_right
    ,0.5*arcminTOradians,cosmo);

  Lens lens(&seed,zs,cosmo);
  lens.moveinMainHalo(treeh,true);

  GridMap gmap(&lens,500,center.x,range);
  
  gmap.writeFitsUniform<float>(LensingVariable::KAPPA,"kappa.fits");
  gmap.writeFitsUniform<float>(LensingVariable::GAMMA,"gamma.fits");
  gmap.writeFitsUniform<float>(LensingVariable::GAMMA1,"gamma1.fits");
  gmap.writeFitsUniform<float>(LensingVariable::GAMMA2,"gamma2.fits");
  gmap.writeFitsUniform<float>(LensingVariable::GAMMA3,"gamma3.fits");
  gmap.writeFitsUniform<float>(LensingVariable::ALPHA,"alpha.fits");
  gmap.writeFitsUniform<float>(LensingVariable::ALPHA1,"alpha1.fits");
  gmap.writeFitsUniform<float>(LensingVariable::ALPHA2,"alpha2.fits");
  gmap.writeFitsUniform<float>(LensingVariable::EigenV,"eigenv.fits");
  gmap.writeFitsUniform<float>(LensingVariable::INVMAG,"invmag.fits");

  PixelMap<float> pmap = gmap.writePixelMap<float>(LensingVariable::KAPPA);

  std::cout << " Sum of kappa map " << pmap.sum()/pmap.size() << std::endl;
  
}

**Comment by rbmetcalf** [comment]
@camilaolave why did you remove  the initialization?
```
Point_2d ll_hr, ur_hr;
 ll_hr = ur_hr = crit.critcurve[0].x; 
```

**Comment by rbmetcalf** [comment]
Line 1201.  Isn't this resetting `ur` and `ll` for each shell?
```
 ur[0] = MAX(ur[0] , gal_position_flat[index].y[0]);
 ur[1] = MAX(ur[1] , gal_position_flat[index].y[1]);
 ll[0] = MIN(ll[0] , gal_position_flat[index].y[0]);
 ll[1] = MIN(ll[1] , gal_position_flat[index].y[1]);
```
Which is then used to find `inv_area_angle` on lines 1296-7.

**Comment by camilaolave** [comment]
Yes, line 1201 is part of the old implementation, when I was switching inv_area according to each shell. Now I use a global_ur/ll so I need to remove that

**Comment by camilaolave** [comment]
Which line is this: 
```
Point_2d ll_hr, ur_hr;
 ll_hr = ur_hr = crit.critcurve[0].x;
``` 


I might have rephrase it. I will check

**Comment by rbmetcalf** [comment]
It used to be between lines 458 and 459.  I'm looking at it in the change log.

**Comment by rbmetcalf** [comment]
I'm making progress.  I just need to make additional checks.

**Comment by rbmetcalf** [comment]
I have pushed a new version.  It corrects the essential problem.

However, it still does not agree exactly with the former LensHaloHalos.  I am trying to figure out what exactly the difference is and which one should be more trusted.  I've got to work on some other things right now though.

**Comment by rbmetcalf** [comment]
Turns out there was an error in LensHaloHalos.  Now it is in agreement with LensHaloH to the degree you would expect.
